### ISSUE TITLE
EPS Meteograms Broken With OpenData Update

### ISSUE THREAD

**Issue by csteele2** [csteele2/Wx4Colab#3]
EPS Meteograms notebook is broken with OpenData update. Fix will include:

- support for 0.25 degree data
- AIFS (though its deterministic)

Currently waiting for pypi to update with ecmwf-opendata 0.3.0.

**Comment by wreed1989** [comment]
Hi, Caleb. What was the fix that cleared the 'string indices must be integers' TypeError? I've combed through my code adapted from your EPS_Meteograms notebook and I'm still unable to get past it. I've even tried copying/pasting your exact code in the notebook and adding the current date to see if I'm just overlooking something. Appreciate the help!
